package com.fooddelivery.restaurant.mapper;

import com.fooddelivery.restaurant.dto.RestaurantRequest;
import com.fooddelivery.restaurant.dto.RestaurantResponse;
import com.fooddelivery.restaurant.model.Restaurant;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.time.LocalDateTime;

@Mapper(componentModel = "spring", imports = {LocalDateTime.class})
public interface RestaurantMapper {
    
    RestaurantMapper INSTANCE = Mappers.getMapper(RestaurantMapper.class);
    
    @Mapping(target = "id", ignore = true)              // ✅ Ignore ID - will be generated by DB
    @Mapping(target = "rating", constant = "0.0")
    @Mapping(target = "totalReviews", constant = "0")
    @Mapping(target = "createdAt", expression = "java(LocalDateTime.now())")
    @Mapping(target = "updatedAt", expression = "java(LocalDateTime.now())")
    @Mapping(target = "description", source = "description")
    @Mapping(target = "operatingHours", source = "operatingHours")
    Restaurant toRestaurant(RestaurantRequest request);
    
    RestaurantResponse toResponse(Restaurant restaurant);
}